export const HardSkills = [
	{ skill: "Figma.png", skillName: "" },
	{ skill: "UI-&-UX.png", skillName: "" },
	{ skill: "Python.png", skillName: "" },
	{ skill: "PHP.png", skillName: "" },
	{ skill: "Angular.png", skillName: ""},
	{ skill: "Laravel.png", skillName: ""},
	{ skill: "HTML.webp", skillName: "" },
	{ skill: "CSS.png", skillName: "" },
	{ skill: "React.png", skillName: "" },
	{ skill: "Java-Script.webp", skillName: "" },
	{ skill: "TypeScript.png", skillName: "" },
	{ skill: "Node-Js.png", skillName: "" },
	{ skill: "Java.png", skillName: "" },
	{ skill: "Bootstrap.png", skillName: "" },
	{ skill: "Git.png", skillName: "" },
	{ skill: "XAMP.png", skillName: "" },
	{ skill: "Prisma.png", skillName: "" },
	{ skill: "MySQL.png", skillName: "" },
	{ skill: "PostgreSQL.png", skillName: "" },
	{ skill: "MongoDB.png", skillName: "" },
	{ skill: "Linux.png", skillName: "" },
	{ skill: "Windows.png", skillName: "" },
	{ skill: "Arduino.png", skillName: "" },
	{ skill: "Docker.webp", skillName: "" },
];